.TH ef 1
.SH NAME
ef \- Utility to run a program under the Electric Fence memory debugger

.SH SYNOPSIS
\fBef\fR PROGRAM [ARGS...]

.SH DESCRIPTION
The \fIef\fR command is used to launch another program under the
Electric Fence memory debugger.  It sets up appropriate environment
variables and then launches the specified program with the specified
arguments.  See efence (3) manual page for more details about Electric
Fence.

.SH SEE ALSO
.BR efence (3)

.SH AUTHORS
Electric Fence was written by Bruce Perens
.br
This manual page was written by Petr Machata <pmachata@redhat.com>
